<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Documentation icons
    |--------------------------------------------------------------------------
    |
    | IconsMind
    |
    */

    'getting-started' => 'insert_drive_file',
    'installation' => 'power',
    'license' => 'copyright',
    'technologies' => 'settings_input_composite',
    'general' => 'info_outline',
    'requirements' => 'done_all',
    'updating' => 'get_app',
    'scripts' => 'description',
    'styling' => 'format_paint',
    'build-files' => 'build',
    'configuration' => 'assignment_turned_in',
    'customization' => 'tune',
    'stripe' => 'payment',
    '2checkout' => 'payment',
    'landing-page-blocks' => 'chrome_reader_mode',
    'form-templates' => 'contact_mail',
    'email-templates' => 'mail_outline',
    'getting-started' => 'launch',
    'media' => 'perm_media',
    'media-browser' => 'perm_media',
    'account' => 'account_box',
    'profile' => 'fingerprint',
    'plan' => 'card_membership',
    'plans' => 'card_membership',
    'users' => 'people',
    'resellers' => 'card_travel',
    'admin' => 'security',
    'managed-installation' => 'headset_mic',
    'proximity-update' => 'add_location',
    'demo' => 'flight_takeoff',
    'download-apps' => 'cloud_download',
    'download-app' => 'cloud_download',
    'translations' => 'language',
    'login' => 'lock_open',
    'landing-pages' => 'flight_land',
    'lists-and-forms' => 'contact_mail',
    'funnels' => 'filter_list',
    'introduction' => 'fas fa-chalkboard-teacher',
    'email-campaigns' => 'mail_outline',
    'nearby-notifications' => 'tap_and_play',
    'proximity-app' => 'phonelink_ring',
    'about-Nearby-Notifications' => 'phonelink_ring',
    'troubleshooting' => 'headset_mic',
    'generate-google-key' => 'vpn_key',
    'modules' => 'dashboard',
    'updates' => 'update',
    'beacons' => 'wifi_tethering',
    'notifications' => 'far fa-comment-alt',
    'Nearby-Notifications' => 'phonelink_ring',
    'QR' => 'fas fa-qrcode',
    'QR-code' => 'fas fa-qrcode',
    'settings' => 'settings',
    'content' => 'far fa-save',
    'deals' => 'store',
    'coupons' => 'redeem',
    'rewards' => 'beenhere',
    'business-cards' => 'account_circle',
    'videos' => 'video_library',
    'pages' => 'insert_drive_file',
    'google-key' => 'vpn_key',
    'analytics' => 'insert_chart',
    'views' => 'pageview',
    '' => '',
];